import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import { validateRequest } from "@/lib/lucia"
import { SessionProvider } from "@/providers/Session.provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const sessionData = await validateRequest()
  console.log(sessionData)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider value={sessionData}>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  )
}
